// Migrated sample data from the supplied prototype. Replace with verified catalogue before launch.
export const products = [
  {
    id: "aeris-20",
    brand: "Aeris",
    name: "Base 20",
    kw: 2,
    room: [10, 18],
    mode: "cool",
    db: 23,
    cls: "A++",
    scop: "3,9",
    price: 179900,
    tier: "value",
    badge: "value",
    tag: "Kis hálószobához, ha csak hűtésre kell.",
    why: "A legkisebb helyiségekhez a legolcsóbb út. Nem fűtésre való: -7 °C alatt már nem gazdaságos vele fűteni, ezért csak nyári komfortra ajánljuk.",
    yes: [
      "Kis háló vagy dolgozó, 18 m² alatt",
      "Csak nyári hűtés a cél",
      "Szűk a keret",
    ],
    no: [
      "Fűteni is szeretnél vele",
      "Nappaliba, nyitott térbe kerülne",
      "Fontos a nagyon halk éjszakai üzem",
    ],
  },
  {
    id: "aeris-26",
    brand: "Aeris",
    name: "Base 26",
    kw: 2.6,
    room: [15, 25],
    mode: "both",
    db: 21,
    cls: "A++",
    scop: "4,1",
    price: 219900,
    tier: "value",
    badge: "value",
    tag: "A legjobb ár/érték a tipikus hálószobához.",
    why: "Ebben a kategóriában ez adja a legtöbbet forintért: rendes inverter, tisztességes hangnyomás, átmeneti időszakban fűtésre is jó. Nem csendrekord, de a legtöbb lakásban bőven elég.",
    yes: [
      "15–25 m² háló vagy dolgozó",
      "Tavasszal-ősszel rá is fűtenél",
      "Jó ár/érték a szempont",
    ],
    no: [
      "Téli főfűtésnek szánod",
      "Nagyon halk üzem a fő elvárás",
      "Látszó helyre kerül és számít a megjelenés",
    ],
  },
  {
    id: "aeris-35",
    brand: "Aeris",
    name: "Base 35",
    kw: 3.5,
    room: [25, 35],
    mode: "both",
    db: 22,
    cls: "A++",
    scop: "4,0",
    price: 249900,
    tier: "value",
    badge: "value",
    tag: "Nappalihoz, ha a keret a fő szempont.",
    why: "Ugyanaz a logika, mint a Base 26-nál, egy mérettel feljebb. Átlagos nappaliig jól viszi, de nyitott konyha-nappaliban már érdemes feljebb lépni.",
    yes: [
      "25–35 m² nappali",
      "Elsősorban hűtés, kiegészítő fűtés",
      "Árérzékeny beruházás",
    ],
    no: [
      "Nyitott, 40 m² feletti légtér",
      "Fő fűtésként használnád",
      "Fontos a prémium megjelenés",
    ],
  },
  {
    id: "nordiq-26",
    brand: "Nordiq",
    name: "Comfort 26",
    kw: 2.6,
    room: [15, 25],
    mode: "both",
    db: 19,
    cls: "A+++",
    scop: "4,6",
    price: 299900,
    tier: "rec",
    badge: "quiet",
    tag: "Hálószobába, ahol a csend számít.",
    why: "19 dB-es éjszakai fokozattal ez a leghalkabb gép a kínálatunkban ebben a méretben. Alvós helyiségbe ez az a különbség, amit tényleg észreveszel.",
    yes: [
      "Hálószoba, gyerekszoba",
      "Érzékeny vagy a zajra",
      "Hosszú távra tervezel",
    ],
    no: [
      "Csak nyáron, ritkán használnád",
      "A legalacsonyabb ár a cél",
      "Nagy, nyitott légtérbe kellene",
    ],
  },
  {
    id: "nordiq-35",
    brand: "Nordiq",
    name: "Comfort 35",
    kw: 3.5,
    room: [25, 35],
    mode: "both",
    db: 20,
    cls: "A+++",
    scop: "4,5",
    price: 329900,
    tier: "rec",
    badge: "rec",
    tag: "A legtöbb magyar nappaliba ezt tesszük be.",
    why: "Ezt szereljük a legtöbbet, és ezért ajánljuk: jó hatásfok, halk működés, korrekt fűtési teljesítmény, és nem fizetsz rá olyan funkciókra, amiket soha nem kapcsolsz be.",
    yes: [
      "25–35 m² nappali vagy nyitott tér",
      "Hűtés és rendszeres fűtés is kell",
      "Egy gépet szeretnél hosszú évekre",
    ],
    no: [
      "Ez a gép a ház fő fűtése lenne",
      "18 m² alatti kis szoba",
      "Nagyon szűk a keret",
    ],
  },
  {
    id: "nordiq-air-35",
    brand: "Nordiq",
    name: "Air+ 35",
    kw: 3.5,
    room: [25, 35],
    mode: "both",
    db: 21,
    cls: "A+++",
    scop: "4,4",
    price: 379900,
    tier: "rec",
    badge: "",
    tag: "Ha a levegő minősége is szempont.",
    why: "Ugyanaz az alap, mint a Comfort 35, plusz komolyabb szűrés. Allergiaszezonban és városi, forgalmas utcára néző lakásban van értelme a felárnak — máshol nincs.",
    yes: [
      "Forgalmas utcára néző lakás",
      "Pollenre érzékeny a család",
      "Sokat vagy otthon",
    ],
    no: [
      "Csendes, zöldövezeti környezet",
      "A szűrőcsere költsége zavar",
      "A legolcsóbb megoldást keresed",
    ],
  },
  {
    id: "valtek-35",
    brand: "Valtek",
    name: "Nordic 35",
    kw: 3.5,
    room: [25, 35],
    mode: "heat",
    db: 23,
    cls: "A+++",
    scop: "5,1",
    price: 419900,
    tier: "rec",
    badge: "heat",
    tag: "Télen is dolgozik: -25 °C-ig fűt.",
    why: "Ha a klímát tényleg fűtésre veszed, nem mindegy, mit tud -10 °C alatt. Ez a széria erre készült: alacsony külső hőmérsékleten is tartja a teljesítményt, ahol az átlagos gép már visszaesik.",
    yes: [
      "Gázfűtés kiváltása vagy kiegészítése",
      "Télen is ezzel fűtenél",
      "Jól szigetelt, 25–35 m² tér",
    ],
    no: [
      "Csak nyári hűtés a cél",
      "Rosszul szigetelt, huzatos épület",
      "A beszerzési ár a fő szempont",
    ],
  },
  {
    id: "valtek-50",
    brand: "Valtek",
    name: "Nordic 50",
    kw: 5,
    room: [35, 50],
    mode: "heat",
    db: 25,
    cls: "A+++",
    scop: "5,0",
    price: 489900,
    tier: "rec",
    badge: "heat",
    tag: "Nagy nappali fűtésre és hűtésre.",
    why: "A Nordic 35 nagyobb testvére. Nyitott konyha-nappaliba, ahol a klíma a téli fűtés érdemi része, nem csak ráfűtés.",
    yes: [
      "35–50 m² nyitott légtér",
      "Fűtés is fő funkció",
      "Egy gép vinné a földszintet",
    ],
    no: ["Kis hálószoba", "Csak hűtés kell", "Halk üzem az első szempont"],
  },
  {
    id: "sensa-26",
    brand: "Sensa",
    name: "Design 26",
    kw: 2.6,
    room: [15, 25],
    mode: "both",
    db: 19,
    cls: "A+++",
    scop: "4,6",
    price: 459900,
    tier: "premium",
    badge: "premium",
    tag: "Amikor a beltéri egység látszik, és ez zavar.",
    why: "Technikailag a Comfort 26 szintje, a felár a formatervezésért és az anyaghasználatért van. Akkor éri meg, ha a gép reprezentatív térbe kerül — máshol a Comfort 26 ugyanazt tudja olcsóbban.",
    yes: [
      "Igényesen berendezett tér",
      "Látszó helyre kerül a beltéri egység",
      "Fontos a részletminőség",
    ],
    no: [
      "Rejtett vagy mellékes helyre kerül",
      "Ár/érték a fő szempont",
      "Fűtési teljesítmény a döntő",
    ],
  },
  {
    id: "sensa-35",
    brand: "Sensa",
    name: "Pro 35",
    kw: 3.5,
    room: [25, 35],
    mode: "both",
    db: 18,
    cls: "A+++",
    scop: "4,8",
    price: 529900,
    tier: "premium",
    badge: "premium",
    tag: "A legcsendesebb és leghatékonyabb a kínálatban.",
    why: "18 dB és A+++ hatásfok — ez ma a felső határ. Prémium kategória, prémium áron. Nem mindenkinek kell, de aki ezt keresi, ennél lejjebb nem érdemes adnia.",
    yes: [
      "Prémium kategória a cél",
      "Hálószoba, ahol a csend szent",
      "Hosszú távú, alacsony fogyasztás",
    ],
    no: [
      "Ár/érték alapon döntesz",
      "Ritkán használt helyiség",
      "Kültéri elhelyezés amúgy is korlátos",
    ],
  },
  {
    id: "sensa-50",
    brand: "Sensa",
    name: "Pro 50",
    kw: 5,
    room: [35, 50],
    mode: "both",
    db: 19,
    cls: "A+++",
    scop: "4,7",
    price: 619900,
    tier: "premium",
    badge: "premium",
    tag: "Nagy térbe, prémium elvárásokkal.",
    why: "Nagy nyitott térbe a legjobb, amit adni tudunk: halk, hatékony, erős. A felára itt már a teljesítményben is megjelenik, nem csak a megjelenésben.",
    yes: [
      "35–50 m² nyitott nappali",
      "Prémium anyag- és hangminőség",
      "Hűtés és fűtés egyaránt",
    ],
    no: [
      "Kis helyiség",
      "Költségérzékeny projekt",
      "Csak szezonális használat",
    ],
  },
  {
    id: "nordiq-50",
    brand: "Nordiq",
    name: "Comfort 50",
    kw: 5,
    room: [35, 50],
    mode: "both",
    db: 24,
    cls: "A++",
    scop: "4,3",
    price: 399900,
    tier: "rec",
    badge: "rec",
    tag: "Nyitott konyha-nappalihoz, kiegyensúlyozottan.",
    why: "Nagyobb térbe ez a józan középút: elég erő, korrekt hatásfok, nem elszállt ár. Ahol nem elvárás a prémium csend, itt nincs miért többet költeni.",
    yes: [
      "35–50 m² nyitott tér",
      "Hűtés és ráfűtés",
      "Kiegyensúlyozott ár/érték",
    ],
    no: ["Hálószoba", "A csend a fő szempont", "Fő fűtésnek szánod"],
  },
];
export const heatpumps = [
  {
    id: "nordiq-aqua-6",
    sku: "TV-HP-NRD-A6",
    brand: "Nordiq",
    name: "Aqua 6",
    kw: 6,
    use: "new",
    flow: "35–45 °C",
    fn: ["heat", "dhw"],
    area: [80, 120],
    price: 2690000,
    tier: "value",
    tag: "Új építésű családi házhoz, padlófűtéssel.",
    why: "Jól szigetelt új háznál alacsony előremenő hőmérséklettel a leghatékonyabb a hőszivattyú. Ez a gép pontosan erre készült — meglévő, radiátoros rendszerbe nem ezt tennénk.",
    yes: [
      "Új építésű, jól szigetelt ház",
      "Padlófűtés a hőleadó",
      "80–120 m² fűtött terület",
    ],
    no: [
      "Régi, radiátoros rendszer",
      "Magas előremenő hőmérséklet kell",
      "Hűtésre is használnád",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (180 l)",
      "szabályozás és időjáráskövetés",
      "hidraulikai elemek, szerelvények",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "nordiq-aqua-8",
    sku: "TV-HP-NRD-A8",
    brand: "Nordiq",
    name: "Aqua 8",
    kw: 8,
    use: "both",
    flow: "35–55 °C",
    fn: ["heat", "dhw", "cool"],
    area: [110, 160],
    price: 3190000,
    tier: "rec",
    tag: "A legtöbb családi házba ezt a rendszert tervezzük.",
    why: "Széles előremenő tartomány, így vegyes hőleadóval — padlófűtés a földszinten, radiátor az emeleten — is jól dolgozik. Aktív hűtésre is alkalmas, ha padlófűtés vagy fan-coil van.",
    yes: [
      "110–160 m² fűtött terület",
      "Vegyes vagy padlófűtéses rendszer",
      "Nyáron hűteni is szeretnél",
    ],
    no: [
      "Nagyon kicsi, jól szigetelt ház",
      "Csak HMV-t akarsz megoldani",
      "Ipari léptékű igény",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (200 l)",
      "puffertároló, ha a rendszer igényli",
      "szabályozás, hűtési üzemmód",
      "hidraulikai elemek, szerelvények",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "valtek-terra-10",
    sku: "TV-HP-VLT-T10",
    brand: "Valtek",
    name: "Terra 10",
    kw: 10,
    use: "retrofit",
    flow: "45–65 °C",
    fn: ["heat", "dhw"],
    area: [120, 180],
    price: 3690000,
    tier: "rec",
    tag: "Gázkazán kiváltására, meglévő radiátoros rendszerbe.",
    why: "A legtöbb korszerűsítésnél az a kérdés, elbírja-e a meglévő radiátoros rendszer. Ez a széria 65 °C-ig megy fel, így sok esetben a radiátorok cseréje nélkül is működik — de ezt minden projektnél kiszámoljuk.",
    yes: [
      "Meglévő ház, radiátoros fűtés",
      "Gázkazánt váltanál ki",
      "120–180 m² fűtött terület",
    ],
    no: [
      "Szigeteletlen, nagy hőveszteségű épület",
      "Hűtésre is kellene",
      "Új építésű, padlófűtéses ház",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (200 l)",
      "puffertároló",
      "meglévő rendszer bekötése, szűrés",
      "szabályozás",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "valtek-terra-14",
    sku: "TV-HP-VLT-T14",
    brand: "Valtek",
    name: "Terra 14",
    kw: 14,
    use: "retrofit",
    flow: "45–65 °C",
    fn: ["heat", "dhw"],
    area: [170, 240],
    price: 4290000,
    tier: "rec",
    tag: "Nagyobb, meglévő családi házhoz.",
    why: "Ugyanaz a felépítés, mint a Terra 10-nél, nagyobb teljesítménnyel. Nagy alapterületnél a méretezés hibája drágán jön vissza, ezért itt mindig kérünk fűtési számítást vagy korábbi fogyasztási adatot.",
    yes: [
      "170–240 m² fűtött terület",
      "Meglévő, radiátoros vagy vegyes rendszer",
      "Nagy HMV-igény",
    ],
    no: [
      "Kis alapterület",
      "Nincs hely a beltéri egységnek és a tárolóknak",
      "Szakaszos, ritka használat",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (300 l)",
      "puffertároló",
      "meglévő rendszer bekötése",
      "szabályozás",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "aeris-hydro-8",
    sku: "TV-HP-AER-H8",
    brand: "Aeris",
    name: "Hydro 8 Komplett",
    kw: 8,
    use: "new",
    flow: "35–50 °C",
    fn: ["heat", "dhw"],
    area: [100, 150],
    price: 2890000,
    tier: "value",
    tag: "Komplett csomag új építéshez, kedvezőbb áron.",
    why: "Előre összeállított rendszer: a gép, a tároló és a szabályozás egy gyártótól, egy garanciával. Kevesebb a tervezői szabadság, cserébe olcsóbb és gyorsabban kivitelezhető — tipikus új építésű háznál ez jó alku.",
    yes: [
      "Új építés, szokványos elrendezés",
      "Padlófűtés",
      "Árérzékeny beruházás",
    ],
    no: [
      "Egyedi hidraulikai igény",
      "Hűtés is kell",
      "Meglévő rendszerhez illesztenéd",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "integrált HMV tároló (190 l)",
      "gyári szabályozás",
      "alap hidraulikai csomag",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "sensa-thermo-12",
    sku: "TV-HP-SNS-T12",
    brand: "Sensa",
    name: "Thermo 12 Pro",
    kw: 12,
    use: "both",
    flow: "35–60 °C",
    fn: ["heat", "dhw", "cool"],
    area: [150, 210],
    price: 4990000,
    tier: "premium",
    tag: "Prémium rendszer fűtésre, hűtésre és melegvízre.",
    why: "A legjobb hatásfok és a legcsendesebb kültéri egység a kínálatunkban, komoly szabályozással és energiamonitorral. Akkor éri meg, ha a fogyasztás és a komfort évtizedes távon számít.",
    yes: [
      "150–210 m² fűtött terület",
      "Fűtés, hűtés és HMV egy rendszerben",
      "Fontos a fogyasztás követése",
    ],
    no: ["Kis ház", "Rövid távon gondolkodsz", "A beruházási ár a fő szempont"],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (300 l)",
      "puffertároló",
      "hűtési kör és páratartalom-védelem",
      "energiamonitor, távfelügyelet",
      "kivitelezés és beüzemelés",
    ],
  },
];
