export { products } from "./catalogue-products.js";

export const heatpumps = [
  {
    id: "nordiq-aqua-6",
    sku: "TV-HP-NRD-A6",
    brand: "Nordiq",
    name: "Aqua 6",
    kw: 6,
    use: "new",
    flow: "35–45 °C",
    fn: ["heat", "dhw"],
    area: [80, 120],
    price: 2690000,
    tier: "value",
    tag: "Új építésű családi házhoz, padlófűtéssel.",
    why: "Jól szigetelt új háznál alacsony előremenő hőmérséklettel a leghatékonyabb a hőszivattyú. Ez a gép pontosan erre készült — meglévő, radiátoros rendszerbe nem ezt tennénk.",
    yes: [
      "Új építésű, jól szigetelt ház",
      "Padlófűtés a hőleadó",
      "80–120 m² fűtött terület",
    ],
    no: [
      "Régi, radiátoros rendszer",
      "Magas előremenő hőmérséklet kell",
      "Hűtésre is használnád",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (180 l)",
      "szabályozás és időjáráskövetés",
      "hidraulikai elemek, szerelvények",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "nordiq-aqua-8",
    sku: "TV-HP-NRD-A8",
    brand: "Nordiq",
    name: "Aqua 8",
    kw: 8,
    use: "both",
    flow: "35–55 °C",
    fn: ["heat", "dhw", "cool"],
    area: [110, 160],
    price: 3190000,
    tier: "rec",
    tag: "A legtöbb családi házba ezt a rendszert tervezzük.",
    why: "Széles előremenő tartomány, így vegyes hőleadóval — padlófűtés a földszinten, radiátor az emeleten — is jól dolgozik. Aktív hűtésre is alkalmas, ha padlófűtés vagy fan-coil van.",
    yes: [
      "110–160 m² fűtött terület",
      "Vegyes vagy padlófűtéses rendszer",
      "Nyáron hűteni is szeretnél",
    ],
    no: [
      "Nagyon kicsi, jól szigetelt ház",
      "Csak HMV-t akarsz megoldani",
      "Ipari léptékű igény",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (200 l)",
      "puffertároló, ha a rendszer igényli",
      "szabályozás, hűtési üzemmód",
      "hidraulikai elemek, szerelvények",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "valtek-terra-10",
    sku: "TV-HP-VLT-T10",
    brand: "Valtek",
    name: "Terra 10",
    kw: 10,
    use: "retrofit",
    flow: "45–65 °C",
    fn: ["heat", "dhw"],
    area: [120, 180],
    price: 3690000,
    tier: "rec",
    tag: "Gázkazán kiváltására, meglévő radiátoros rendszerbe.",
    why: "A legtöbb korszerűsítésnél az a kérdés, elbírja-e a meglévő radiátoros rendszer. Ez a széria 65 °C-ig megy fel, így sok esetben a radiátorok cseréje nélkül is működik — de ezt minden projektnél kiszámoljuk.",
    yes: [
      "Meglévő ház, radiátoros fűtés",
      "Gázkazánt váltanál ki",
      "120–180 m² fűtött terület",
    ],
    no: [
      "Szigeteletlen, nagy hőveszteségű épület",
      "Hűtésre is kellene",
      "Új építésű, padlófűtéses ház",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (200 l)",
      "puffertároló",
      "meglévő rendszer bekötése, szűrés",
      "szabályozás",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "valtek-terra-14",
    sku: "TV-HP-VLT-T14",
    brand: "Valtek",
    name: "Terra 14",
    kw: 14,
    use: "retrofit",
    flow: "45–65 °C",
    fn: ["heat", "dhw"],
    area: [170, 240],
    price: 4290000,
    tier: "rec",
    tag: "Nagyobb, meglévő családi házhoz.",
    why: "Ugyanaz a felépítés, mint a Terra 10-nél, nagyobb teljesítménnyel. Nagy alapterületnél a méretezés hibája drágán jön vissza, ezért itt mindig kérünk fűtési számítást vagy korábbi fogyasztási adatot.",
    yes: [
      "170–240 m² fűtött terület",
      "Meglévő, radiátoros vagy vegyes rendszer",
      "Nagy HMV-igény",
    ],
    no: [
      "Kis alapterület",
      "Nincs hely a beltéri egységnek és a tárolóknak",
      "Szakaszos, ritka használat",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (300 l)",
      "puffertároló",
      "meglévő rendszer bekötése",
      "szabályozás",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "aeris-hydro-8",
    sku: "TV-HP-AER-H8",
    brand: "Aeris",
    name: "Hydro 8 Komplett",
    kw: 8,
    use: "new",
    flow: "35–50 °C",
    fn: ["heat", "dhw"],
    area: [100, 150],
    price: 2890000,
    tier: "value",
    tag: "Komplett csomag új építéshez, kedvezőbb áron.",
    why: "Előre összeállított rendszer: a gép, a tároló és a szabályozás egy gyártótól, egy garanciával. Kevesebb a tervezői szabadság, cserébe olcsóbb és gyorsabban kivitelezhető — tipikus új építésű háznál ez jó alku.",
    yes: [
      "Új építés, szokványos elrendezés",
      "Padlófűtés",
      "Árérzékeny beruházás",
    ],
    no: [
      "Egyedi hidraulikai igény",
      "Hűtés is kell",
      "Meglévő rendszerhez illesztenéd",
    ],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "integrált HMV tároló (190 l)",
      "gyári szabályozás",
      "alap hidraulikai csomag",
      "kivitelezés és beüzemelés",
    ],
  },
  {
    id: "sensa-thermo-12",
    sku: "TV-HP-SNS-T12",
    brand: "Sensa",
    name: "Thermo 12 Pro",
    kw: 12,
    use: "both",
    flow: "35–60 °C",
    fn: ["heat", "dhw", "cool"],
    area: [150, 210],
    price: 4990000,
    tier: "premium",
    tag: "Prémium rendszer fűtésre, hűtésre és melegvízre.",
    why: "A legjobb hatásfok és a legcsendesebb kültéri egység a kínálatunkban, komoly szabályozással és energiamonitorral. Akkor éri meg, ha a fogyasztás és a komfort évtizedes távon számít.",
    yes: [
      "150–210 m² fűtött terület",
      "Fűtés, hűtés és HMV egy rendszerben",
      "Fontos a fogyasztás követése",
    ],
    no: ["Kis ház", "Rövid távon gondolkodsz", "A beruházási ár a fő szempont"],
    parts: [
      "kültéri egység",
      "beltéri hidraulikai modul",
      "HMV tároló (300 l)",
      "puffertároló",
      "hűtési kör és páratartalom-védelem",
      "energiamonitor, távfelügyelet",
      "kivitelezés és beüzemelés",
    ],
  },
];

